<a href="https://colab.research.google.com/github/vcdemy/20230613/blob/main/20230801%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20230801筆記

## Object Oriented Programming, OOP

函式定義:

```python
def foo():
  print("Hello World!")
```

函式呼叫:
```python
foo()
```

類別定義:

```python
class Sprite:
  pass
```

產生物件 (Instantiation):
```python
Sprite()
```

物件(Object)實際上就是類別(Class)的實例(Instance)。

In [1]:
class Sprite:
  pass

In [2]:
x = Sprite()

In [3]:
type(x)

__main__.Sprite

In [4]:
x

In [5]:
hex(id(x))

'0x7d16e25139a0'

In [6]:
x.x = 100
x.y = -100
x.size = 100
x.direction = 90

In [7]:
x.__dict__

{'x': 100, 'y': -100, 'size': 100, 'direction': 90}

In [8]:
y = Sprite()

In [9]:
y.__dict__

{}

In [30]:
class Sprite:
  def __init__(self, x=0, y=0, size=100, direction=90):
    self.x = x
    self.y = y
    self.size = size
    self.direction = direction
  def move_x(self, x=10):
    self.x += x

In [11]:
x1 = Sprite()

In [12]:
x1.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90}

In [13]:
y1 = Sprite()

In [14]:
y1.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90}

In [15]:
x1.move_x()

In [16]:
x1.__dict__

{'x': 10, 'y': 0, 'size': 100, 'direction': 90}

## 繼承(Inheritance)

In [18]:
class Alien1(Sprite):
  pass

In [19]:
x2 = Alien1()

In [20]:
x2.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90}

In [21]:
x2.move_x()

In [22]:
x2.__dict__

{'x': 10, 'y': 0, 'size': 100, 'direction': 90}

In [29]:
class Alien2(Sprite):
  def __init__(self, x=0, y=0, size=100, direction=90, lives=5):
    super().__init__(x, y, size, direction)
    self.lives = lives
  def move_y(self, y=10):
    self.y += y

In [24]:
x3 = Alien2()

In [25]:
x3.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90, 'lives': 5}

In [26]:
x4 = Alien2(100, 50, 50, 90, 3)

In [27]:
x4.__dict__

{'x': 100, 'y': 50, 'size': 50, 'direction': 90, 'lives': 3}

## Numpy, MatPlotLib, Pandas

## Numpy, Plotly, Pandas

### NumPy

* ndarray (多維陣列)
* ufunc (通用函式)

In [31]:
import numpy as np

In [34]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
X = np.arange(25).reshape(5, 5)

In [36]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### indexing

In [37]:
X[2, 2]

12

### Fancy Indexing

In [38]:
X[[1,2,3],[0, 1, 2]]

array([ 5, 11, 17])

### Boolean Indexing

In [39]:
X > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
np.where(X>10, X, 0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])