<a href="https://colab.research.google.com/github/vcdemy/20230613/blob/main/20230801%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20230801筆記

## Object Oriented Programming, OOP

函式定義:

```python
def foo():
  print("Hello World!")
```

函式呼叫:
```python
foo()
```

類別定義:

```python
class Sprite:
  pass
```

產生物件 (Instantiation):
```python
Sprite()
```

物件(Object)實際上就是類別(Class)的實例(Instance)。

In [1]:
class Sprite:
  pass

In [2]:
x = Sprite()

In [3]:
type(x)

__main__.Sprite

In [4]:
x

In [5]:
hex(id(x))

'0x7d16e25139a0'

In [6]:
x.x = 100
x.y = -100
x.size = 100
x.direction = 90

In [7]:
x.__dict__

{'x': 100, 'y': -100, 'size': 100, 'direction': 90}

In [8]:
y = Sprite()

In [9]:
y.__dict__

{}

In [30]:
class Sprite:
  def __init__(self, x=0, y=0, size=100, direction=90):
    self.x = x
    self.y = y
    self.size = size
    self.direction = direction
  def move_x(self, x=10):
    self.x += x

In [11]:
x1 = Sprite()

In [12]:
x1.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90}

In [13]:
y1 = Sprite()

In [14]:
y1.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90}

In [15]:
x1.move_x()

In [16]:
x1.__dict__

{'x': 10, 'y': 0, 'size': 100, 'direction': 90}

## 繼承(Inheritance)

In [18]:
class Alien1(Sprite):
  pass

In [19]:
x2 = Alien1()

In [20]:
x2.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90}

In [21]:
x2.move_x()

In [22]:
x2.__dict__

{'x': 10, 'y': 0, 'size': 100, 'direction': 90}

In [29]:
class Alien2(Sprite):
  def __init__(self, x=0, y=0, size=100, direction=90, lives=5):
    super().__init__(x, y, size, direction)
    self.lives = lives
  def move_y(self, y=10):
    self.y += y

In [24]:
x3 = Alien2()

In [25]:
x3.__dict__

{'x': 0, 'y': 0, 'size': 100, 'direction': 90, 'lives': 5}

In [26]:
x4 = Alien2(100, 50, 50, 90, 3)

In [27]:
x4.__dict__

{'x': 100, 'y': 50, 'size': 50, 'direction': 90, 'lives': 3}

## Numpy, MatPlotLib, Pandas

## Numpy, Plotly, Pandas

### NumPy

科學運算的基礎套件，可以很容易的做向量運算。

* ndarray (多維陣列)
* ufunc (通用函式)



In [31]:
import numpy as np

In [34]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
X = np.arange(25).reshape(5, 5)

In [36]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### indexing

In [37]:
X[2, 2]

12

### Fancy Indexing

In [38]:
X[[1,2,3],[0, 1, 2]]

array([ 5, 11, 17])

### Boolean Indexing

In [39]:
X > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
np.where(X>10, X, 0)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 練習

請計算下列ndarray的數值開根號再乘以10之後，有多少人及格。

In [41]:
G = np.random.randint(10, 50, 10)

In [42]:
G

array([41, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [43]:
np.sqrt(G)

array([6.40312424, 6.08276253, 4.89897949, 6.55743852, 5.91607978,
       5.29150262, 6.92820323, 4.12310563, 4.47213595, 3.87298335])

In [44]:
np.sqrt(G)*10

array([64.03124237, 60.8276253 , 48.98979486, 65.57438524, 59.16079783,
       52.91502622, 69.2820323 , 41.23105626, 44.72135955, 38.72983346])

In [45]:
np.sqrt(G)*10 >= 60

array([ True,  True, False,  True, False, False,  True, False, False,
       False])

In [46]:
(np.sqrt(G)*10 >= 60).sum()

4

### ndarray的常用屬性

In [47]:
G

array([41, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [48]:
G.dtype

dtype('int64')

In [49]:
G.shape

(10,)

In [50]:
G.size

10

### Pandas

* Series
* DataFrame

In [52]:
import pandas as pd

### Series

In [51]:
G

array([41, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [53]:
s = pd.Series(G)

In [54]:
s

0    41
1    37
2    24
3    43
4    35
5    28
6    48
7    17
8    20
9    15
dtype: int64

In [58]:
(np.sqrt(s)*10>=60).sum()

4

In [59]:
s.values

array([41, 37, 24, 43, 35, 28, 48, 17, 20, 15])

### assignment(=) vs .copy()

In [60]:
G

array([41, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [61]:
F = G

In [62]:
F

array([41, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [63]:
F[0] = 51

In [64]:
F

array([51, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [65]:
G

array([51, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [66]:
E = F.copy()

In [67]:
E[0] = 41

In [68]:
E

array([41, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [69]:
F

array([51, 37, 24, 43, 35, 28, 48, 17, 20, 15])

In [70]:
G

array([51, 37, 24, 43, 35, 28, 48, 17, 20, 15])

### Side Note: Tuple immutable!?

In [72]:
m = (1, 2, 3)

In [73]:
m[0] = 4

TypeError: ignored

In [74]:
n = ([1, 2, 3], 4, 5)

In [75]:
type(n)

tuple

In [76]:
n[0][0] = 6

In [77]:
n

([6, 2, 3], 4, 5)

### Series的非整數的index

In [81]:
s1 = pd.Series([1, 2, 3, 4, 5])

In [82]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [83]:
s2 = pd.Series([2, 3, 4, 5, 6], index=list('abcde'))

In [84]:
s2

a    2
b    3
c    4
d    5
e    6
dtype: int64

In [85]:
s1.index = list('bcdef')

In [86]:
s1

b    1
c    2
d    3
e    4
f    5
dtype: int64

In [87]:
s1 + s2

a     NaN
b     4.0
c     6.0
d     8.0
e    10.0
f     NaN
dtype: float64

In [88]:
s1 * s2

a     NaN
b     3.0
c     8.0
d    15.0
e    24.0
f     NaN
dtype: float64

In [89]:
(s1 * s2).values

array([nan,  3.,  8., 15., 24., nan])

### DataFrame

In [90]:
data = np.random.randint(10, 70, (10, 4))

In [91]:
data

array([[39, 18, 68, 61],
       [55, 68, 60, 22],
       [66, 56, 41, 40],
       [41, 22, 10, 63],
       [33, 53, 43, 65],
       [56, 25, 52, 12],
       [35, 16, 43, 43],
       [31, 61, 33, 60],
       [60, 31, 12, 17],
       [46, 66, 11, 21]])

In [92]:
df = pd.DataFrame(data)

In [93]:
df

0   1   2   3
0  39  18  68  61
1  55  68  60  22
2  66  56  41  40
3  41  22  10  63
4  33  53  43  65
5  56  25  52  12
6  35  16  43  43
7  31  61  33  60
8  60  31  12  17
9  46  66  11  21

In [94]:
df.columns = ['國文','英文','數學','理化']

In [95]:
df.index = ['蕭念宜','林慧萍','周哲維','張雅君','吳于庭',
            '關詩婷','黃韻宇','張侑花','李志文','陳如君']

In [96]:
df

國文  英文  數學  理化
蕭念宜  39  18  68  61
林慧萍  55  68  60  22
周哲維  66  56  41  40
張雅君  41  22  10  63
吳于庭  33  53  43  65
關詩婷  56  25  52  12
黃韻宇  35  16  43  43
張侑花  31  61  33  60
李志文  60  31  12  17
陳如君  46  66  11  21

### 練習

請對df裡面所有的科目的成績開根號再乘以10。

#### 方法一:

In [97]:
def sqrtx10(x):
  return np.sqrt(x)*10

In [98]:
sqrtx10([25, 36, 49])

array([50., 60., 70.])

In [99]:
df.apply(sqrtx10)

國文         英文         數學         理化
蕭念宜  62.449980  42.426407  82.462113  78.102497
林慧萍  74.161985  82.462113  77.459667  46.904158
周哲維  81.240384  74.833148  64.031242  63.245553
張雅君  64.031242  46.904158  31.622777  79.372539
吳于庭  57.445626  72.801099  65.574385  80.622577
關詩婷  74.833148  50.000000  72.111026  34.641016
黃韻宇  59.160798  40.000000  65.574385  65.574385
張侑花  55.677644  78.102497  57.445626  77.459667
李志文  77.459667  55.677644  34.641016  41.231056
陳如君  67.823300  81.240384  33.166248  45.825757

In [100]:
df

國文  英文  數學  理化
蕭念宜  39  18  68  61
林慧萍  55  68  60  22
周哲維  66  56  41  40
張雅君  41  22  10  63
吳于庭  33  53  43  65
關詩婷  56  25  52  12
黃韻宇  35  16  43  43
張侑花  31  61  33  60
李志文  60  31  12  17
陳如君  46  66  11  21

#### 方法二:

In [101]:
df.apply(lambda x: np.sqrt(x)*10)

國文         英文         數學         理化
蕭念宜  62.449980  42.426407  82.462113  78.102497
林慧萍  74.161985  82.462113  77.459667  46.904158
周哲維  81.240384  74.833148  64.031242  63.245553
張雅君  64.031242  46.904158  31.622777  79.372539
吳于庭  57.445626  72.801099  65.574385  80.622577
關詩婷  74.833148  50.000000  72.111026  34.641016
黃韻宇  59.160798  40.000000  65.574385  65.574385
張侑花  55.677644  78.102497  57.445626  77.459667
李志文  77.459667  55.677644  34.641016  41.231056
陳如君  67.823300  81.240384  33.166248  45.825757

#### 方法三:

In [104]:
df.applymap(lambda x: np.sqrt(x)*10)

國文         英文         數學         理化
蕭念宜  62.449980  42.426407  82.462113  78.102497
林慧萍  74.161985  82.462113  77.459667  46.904158
周哲維  81.240384  74.833148  64.031242  63.245553
張雅君  64.031242  46.904158  31.622777  79.372539
吳于庭  57.445626  72.801099  65.574385  80.622577
關詩婷  74.833148  50.000000  72.111026  34.641016
黃韻宇  59.160798  40.000000  65.574385  65.574385
張侑花  55.677644  78.102497  57.445626  77.459667
李志文  77.459667  55.677644  34.641016  41.231056
陳如君  67.823300  81.240384  33.166248  45.825757

In [105]:
import math

In [106]:
df.applymap(lambda x: math.sqrt(x)*10)

國文         英文         數學         理化
蕭念宜  62.449980  42.426407  82.462113  78.102497
林慧萍  74.161985  82.462113  77.459667  46.904158
周哲維  81.240384  74.833148  64.031242  63.245553
張雅君  64.031242  46.904158  31.622777  79.372539
吳于庭  57.445626  72.801099  65.574385  80.622577
關詩婷  74.833148  50.000000  72.111026  34.641016
黃韻宇  59.160798  40.000000  65.574385  65.574385
張侑花  55.677644  78.102497  57.445626  77.459667
李志文  77.459667  55.677644  34.641016  41.231056
陳如君  67.823300  81.240384  33.166248  45.825757

In [107]:
df.apply(lambda x: math.sqrt(x)*10)

TypeError: ignored

### 缺失值處理

In [108]:
df1 = df.copy()

In [109]:
df1

國文  英文  數學  理化
蕭念宜  39  18  68  61
林慧萍  55  68  60  22
周哲維  66  56  41  40
張雅君  41  22  10  63
吳于庭  33  53  43  65
關詩婷  56  25  52  12
黃韻宇  35  16  43  43
張侑花  31  61  33  60
李志文  60  31  12  17
陳如君  46  66  11  21

In [110]:
import random

In [111]:
for i in range(5):
  x = random.randint(0, 9)
  y = random.randint(0, 3)
  df1.iloc[x, y] = np.nan

In [112]:
df1

國文    英文    數學  理化
蕭念宜  39.0  18.0  68.0  61
林慧萍  55.0  68.0   NaN  22
周哲維   NaN   NaN  41.0  40
張雅君  41.0  22.0  10.0  63
吳于庭  33.0  53.0  43.0  65
關詩婷  56.0  25.0  52.0  12
黃韻宇  35.0  16.0  43.0  43
張侑花  31.0   NaN   NaN  60
李志文  60.0  31.0  12.0  17
陳如君  46.0  66.0  11.0  21

In [113]:
df1.dropna()

國文    英文    數學  理化
蕭念宜  39.0  18.0  68.0  61
張雅君  41.0  22.0  10.0  63
吳于庭  33.0  53.0  43.0  65
關詩婷  56.0  25.0  52.0  12
黃韻宇  35.0  16.0  43.0  43
李志文  60.0  31.0  12.0  17
陳如君  46.0  66.0  11.0  21